[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "audio_engine"
version = "0.1.0"
requires-python = ">=3.9,<3.13"

[tool.setuptools.packages.find]
where = ["."]
include = ["audio_engine*"]
